package com.ak4n1.turn_management.feature.notification.service.template;

public enum EmailTemplateType {
    WELCOME,
    EMAIL_VERIFICATION,
    PASSWORD_RESET,
    PASSWORD_RESET_CONFIRMATION,
    ACCOUNT_LOCKED,
    APPOINTMENT_CREATED,
    APPOINTMENT_CONFIRMED,
    APPOINTMENT_CANCELLED_BY_USER,
    APPOINTMENT_CANCELLED_BY_ADMIN,
    APPOINTMENT_RESCHEDULED,
    APPOINTMENT_REMINDER
}

